
typedef enum {
    TT_POINT_FLAG_NONE           = 0,

    // If set, the point is the start of a line segment
    // If unset, the point is the start of a quadratic bezier
    TT_POINT_FLAG_LINE           = (1 << 0),
    TT_POINT_FLAG_CONTOUR_END    = (1 << 1),

    // If set, the first point of the contour was off curve, and the parser
    // started with the next point. This is here to be able to compute the 
    // indices of points prior to the parser's processing (in theory)
    TT_POINT_FLAG_CONTOUR_OFFSET = (1 << 2),
    // If set, this point was implicit in the original font outline and 
    // generated byt the parser.
    // See https://developer.apple.com/fonts/TrueType-Reference-Manual/RM01/Chap1.html
    // This is here to be able to compute the indices of points prior to the 
    // parser's processing (in theory)
    TT_POINT_FLAG_GENERATED      = (1 << 3),

    // Only used for MSDF rendering
    TT_POINT_FLAG_RED            = (1 << 4),
    TT_POINT_FLAG_GREEN          = (1 << 5),
    TT_POINT_FLAG_BLUE           = (2 << 6),
} tt_point_flag_enum;

typedef u8 tt_point_flag;

typedef struct {
    i16 x_min;
    i16 y_min;
    i16 x_max;
    i16 y_max;

    u32 num_contours;
    u32 num_segments;
    u32 num_points;

    tt_point_flag* flags;
    v2_i16* points;
} tt_glyph_data;

#include "truetype_parse.h"
#include "truetype_render.h"

