
typedef struct {
    u32 offset;
    u32 length;
} tt_font_table;

typedef struct {
    b8 initialized;

    b8 cmap_sorted;

    i16 loca_format;
    u16 num_glyphs;
    u16 cmap_format;
    // Offset of selected cmap subtable, not cmap table itself
    // Offset is from beginning of file
    u32 cmap_offset;

    u32 max_glyph_points;
    u32 max_glyph_contours;

    tt_font_table head, glyf, hmtx, loca;
} tt_font_info;

typedef enum {
    TT_POINT_FLAG_NONE           = 0b0000000,

    // If set, the point is the start of a line segment
    // If unset, the point is the start of a quadratic bezier
    TT_POINT_FLAG_LINE           = 0b0000001,
    TT_POINT_FLAG_CONTOUR_END    = 0b0000010,

    // If set, the first point of the contour was off curve, and the parser
    // started with the next point. This is here to be able to compute the 
    // indices of points prior to the parser's processing (in theory)
    TT_POINT_FLAG_CONTOUR_OFFSET = 0b0000100,
    // If set, this point was implicit in the original font outline and 
    // generated byt the parser.
    // See https://developer.apple.com/fonts/TrueType-Reference-Manual/RM01/Chap1.html
    // This is here to be able to compute the indices of points prior to the 
    // parser's processing (in theory)
    TT_POINT_FLAG_GENERATED      = 0b0001000,

    // Only used for MSDF rendering
    TT_POINT_FLAG_RED            = 0b0010000,
    TT_POINT_FLAG_GREEN          = 0b0100000,
    TT_POINT_FLAG_BLUE           = 0b1000000,
} tt_point_flag_enum;

typedef u8 tt_point_flag;

typedef struct {
    i16 x_min;
    i16 y_min;
    i16 x_max;
    i16 y_max;

    u32 num_segments;
    u32 num_points;

    tt_point_flag* flags;
    v2_i16* points;
} tt_glyph_data;

void tt_font_init(string8 file, tt_font_info* info);

f32 tt_scale_for_em(string8 file, tt_font_info* info, f32 pixels_per_em);

tt_glyph_data tt_glyph_data_from_index(
    mem_arena* arena, string8 file,
    tt_font_info* info, u32 glyph_index
);

tt_glyph_data tt_glyph_data_from_codepoint(
    mem_arena* arena, string8 file,
    tt_font_info* info, u32 codepoint
);

u32 tt_glyph_index(string8 file, tt_font_info* info, u32 codepoint);

